Models/Shipment.cs
using System.ComponentModel.DataAnnotations;

namespace ThienAnFuni.Models
{
    public class Shipment // Phiếu nhập lô hàng
    {
        [Display(Name = "Mã NH")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Ngày nhập không được để trống")]
        [DataType(DataType.Date)]
        [Display(Name = "Ngày nhập")]
        public DateTime ReceiptDate { get; set; }
        [Required(ErrorMessage = "Tổng giá không được để trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Tổng giá phải là số")]
        [Display(Name = "Tổng tiền")]
        public double TotalPrice { get; set; }

        [Required(ErrorMessage = "Tổng số lượng không được để trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Tổng số lượng phải là số")]
        [Display(Name = "Tổng số lượng")]
        public int TotalQuantity { get; set; }
        [Display(Name = "Ghi chú")]

        public string? Note { get; set; }
        [Display(Name = "Mã NCC")]

        public int SupplierId { get; set; }
        public virtual Supplier? Supplier { get; set; }
        public string ManagerId { get; set; }
        public virtual Manager? Manager { get; set; }
        public virtual ICollection<Goods> Goods { get; set; } = new List<Goods>();


    }
}

Controllers/ShipmentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ThienAnFuni.Helpers;
using ThienAnFuni.Models;

namespace ThienAnFuni.Controllers
{
    [Authorize(Roles = ConstHelper.RoleManager)]
    public class ShipmentsController : Controller
    {
        private const string ShipmentSessionKey = "Shipment";
        private readonly TAF_DbContext _context;

        public ShipmentsController(TAF_DbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["ActiveMenu"] = "Shipment";

            try
            {
                var suppliers = await _context.Suppliers.ToListAsync();

                if (suppliers == null || !suppliers.Any())
                {
                    ViewBag.SupplierErrorMessage = "Không có nhà cung cấp nào trong cơ sở dữ liệu.";
                }

                ViewBag.Suppliers = suppliers;

                return View();
            }
            catch (Exception ex)
            {
                // Ghi log exception và hiển thị lỗi tổng quát
                ViewBag.ErrorMessage = "Đã xảy ra lỗi khi tải dữ liệu: " + ex.Message;
                return View();
            }
        }

        // Lấy danh sách các lô hàng
        [HttpGet]
        public async Task<IActionResult> ListShipment()
        {
            ViewData["ActiveMenu"] = "Shipment";
            try
            {
                var shipments = await _context.Shipments
                    .Include(s => s.Supplier)
                    .Include(s => s.Manager)
                    .Include(s => s.Goods)
                    .ThenInclude(g => g.Product) // Đảm bảo thông tin Product được lấy
                    .ToListAsync();

                return View(shipments); // Trả về View với dữ liệu shipments
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Đã xảy ra lỗi khi tải dữ liệu: " + ex.Message);
            }
        }
        // Xem chi tiết lô hàng
        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            ViewData["ActiveMenu"] = "Shipment";
            try
            {
                var shipment = await _context.Shipments
                    .Include(s => s.Supplier)
                    .Include(s => s.Manager)
                    .Include(s => s.Goods)
                        .ThenInclude(g => g.Product)
                        .ThenInclude(p => p.Category)
                    .FirstOrDefaultAsync(s => s.Id == id);

                if (shipment == null)
                {
                    return NotFound("Không tìm thấy lô hàng");
                }

                return View(shipment);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Đã xảy ra lỗi khi tải dữ liệu: " + ex.Message);
            }
        }


        // Tìm kiếm sản phẩm
        [HttpGet]
        public IActionResult SearchProduct(string keyword)
        {
            var products = _context.Products
                .Where(p => p.IsActive == true && p.Category.IsActive == true && (p.Name.Contains(keyword) || p.Id.ToString() == keyword))
                .Include(p => p.Category)
                .ToList();



            // Cập nhật đường dẫn hình ảnh đầy đủ cho từng sản phẩm
            var result = products.Select(p => new
            {
                p.Id,
                p.Name,
                p.Description,
                p.Price,
                p.Unit,
                p.Material,
                p.Dimension,
                p.Standard,
                p.Color,
                p.Brand,
                p.WarrantyPeriod,
                p.IsActive,
                MainImg = p.MainImg != null ? Url.Content("~/adminThienAn/image_product/" + p.MainImg) : Url.Content("~/adminThienAn/image_product/default.png"),
                CategoryName = p.Category != null ? p.Category.Name : "Không có"
            });

            return Json(result);
        }

        // Thêm sản phẩm vào lô hàng trong session
        [HttpPost]
        public IActionResult AddToShipment(int productId, int quantity, double importPrice)
        {
            // Kiểm tra cơ sở dữ liệu có sẵn hay không
            if (_context.Products == null)
            {
                return StatusCode(500, "Database context is not initialized.");
            }

            // Kiểm tra giá nhập có hợp lệ không
            if (importPrice <= 0)
            {
                return BadRequest("Giá nhập phải lớn hơn 0.");
            }

            // Kiểm tra sản phẩm
            var product = _context.Products.FirstOrDefault(p => p.Id == productId);
            if (product == null)
                return NotFound("Product not found");

            // Lấy lô hàng
            var shipment = GetShipment();
            if (shipment == null)
            {
                return StatusCode(500, "Shipment not found.");
            }

            // Kiểm tra xem Goods có được khởi tạo không
            if (shipment.Goods == null)
            {
                shipment.Goods = new List<Goods>();
            }

            // Tìm sản phẩm trong lô hàng hiện tại
            var goodsItem = shipment.Goods.FirstOrDefault(g => g.ProductId == productId);

            if (goodsItem != null && goodsItem.Quantity < quantity)
            {
                return BadRequest("Số lượng nhập vào lớn hơn số lượng trong kho");
            }

            if (goodsItem != null)
            {
                // Cập nhật số lượng và tổng giá nếu sản phẩm đã tồn tại
                goodsItem.Quantity += quantity;
                goodsItem.TotalPrice = goodsItem.Quantity * importPrice;
            }
            else
            {
                // Thêm sản phẩm mới vào lô hàng
                shipment.Goods.Add(new Goods
                {
                    Product = product,
                    ProductId = product.Id,
                    Quantity = quantity,
                    ImportPrice = importPrice,
                    TotalPrice = importPrice * quantity,
                    ShipmentId = shipment.Id
                });
            }

            // Cập nhật tổng giá và tổng số lượng của lô hàng
            shipment.TotalQuantity = shipment.Goods.Sum(g => g.Quantity);
            shipment.TotalPrice = shipment.Goods.Sum(g => g.TotalPrice);

            SaveShipmentSession(shipment);

            return Json(shipment.Goods.Select(g => new
            {
                g.ProductId,
                ProductName = g?.Product?.Name ?? "N/A",
                ProductImage = $"/adminThienAn/image_product/{g?.Product?.MainImg ?? "default.png"}",
                g.Quantity,
                g.ImportPrice,
                g.TotalPrice
            }));
        }


        //[HttpPost]
        //public IActionResult RemoveFromShipment(int productId)
        //{
        //    var shipment = GetShipment();
        //    var goodsItem = shipment?.Goods?.FirstOrDefault(g => g.ProductId == productId);

        //    if (goodsItem != null)
        //    {
        //        shipment?.Goods?.Remove(goodsItem);
        //        SaveShipmentSession(shipment);

        //        // Trả về danh sách hàng hóa đã cập nhật với thông tin đầy đủ về sản phẩm
        //        return Json(shipment.Goods.Select(g => new
        //        {
        //            g.ProductId,
        //            ProductName = g.Product?.Name ?? "N/A", // Lấy tên sản phẩm
        //            ProductImage = $"/adminThienAn/image_product/{g.Product?.MainImg ?? "default.png"}", // Lấy hình ảnh sản phẩm
        //            g.Quantity,
        //            Category = g.Product?.Category?.Name ?? "N/A", // Lấy tên danh mục
        //            g.ImportPrice
        //        }));
        //    }

        //    return NotFound("Không tìm thấy sản phẩm trong đơn hàng");
        //}

        [HttpPost]
        public IActionResult RemoveFromShipment(int productId)
        {
            var shipment = GetShipment();
            var goodsItem = shipment?.Goods?.FirstOrDefault(g => g.ProductId == productId);

            if (goodsItem != null)
            {
                shipment?.Goods?.Remove(goodsItem);
                SaveShipmentSession(shipment);

                // Nếu danh sách hàng hóa trống, trả về danh sách rỗng
                if (!shipment.Goods.Any())
                {
                    return Json(new List<object>());
                }

                // Trả về danh sách hàng hóa đã cập nhật
                return Json(shipment.Goods.Select(g => new
                {
                    g.ProductId,
                    ProductName = g.Product?.Name ?? "N/A",
                    ProductImage = $"/adminThienAn/image_product/{g.Product?.MainImg ?? "default.png"}",
                    g.Quantity,
                    Category = g.Product?.Category?.Name ?? "N/A",
                    g.ImportPrice
                }));
            }

            return NotFound("Không tìm thấy sản phẩm trong đơn hàng");
        }


        [HttpGet]
        public IActionResult GetShipmentGoods()
        {
            var shipment = GetShipment();
            var result = shipment?.Goods?.Select(g => new
            {
                g.ProductId,
                ProductName = g.Product?.Name ?? "Không có tên",
                ProductImage = g.Product?.MainImg != null ? Url.Content("~/adminThienAn/image_product/" + g.Product.MainImg) : Url.Content("~/adminThienAn/image_product/default.png"),
                g.Quantity,
                Category = g.Product?.Category?.Name ?? "Không có",
                g.ImportPrice
            }).ToList();

            return Json(result);
        }

Views/Shipments/Detail.cshtml
@model Shipment

@{
    ViewData["Title"] = "Chi tiết nhập hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="app-title">
    @*     <ul class="app-breadcrumb breadcrumb side">
    <li class="breadcrumb-item active"><a href="#"><b>Danh sách sản phẩm</b></a></li>
    </ul> *@
    <div id="clock"></div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="row element-button">
                    <div class="col-sm-2">
                        <a class="btn btn-warning btn-sm" asp-controller="Shipments" asp-action="Index" title="Nhập hàng">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            Nhập hàng
                        </a>
                    </div>

                    <div class="col-sm-2">
                        <a class="btn btn-add btn-sm" asp-controller="adminProducts" asp-action="Create" title="Thêm sản phẩm mới">
                            <i class="fas fa-plus"></i>
                            Tạo mới sản phẩm
                        </a>
                    </div>

                    <div class="col-sm-2">
                        <a class="btn btn-add btn-sm" asp-controller="Shipments" asp-action="Index" title="Nhập hàng">
                            <i class="fas fa-plus"></i>
                            Nhập hàng
                        </a>
                    </div>

                </div>

                <h3 class="text-center mb-3">Hóa đơn nhập kho</h3>
                <div class="row">

                    <div class="form-group col-md-2">
                        <label class="control-label">Mã phiếu nhập</label>
                        <input type="text" class="form-control" name="receiptDate" value="#@Model.Id" readonly />
                    </div>

                    <div class="form-group col-md-3">
                        <label class="control-label">Ngày nhập</label>
                        <input type="date" class="form-control" name="receiptDate" value="@Model.ReceiptDate.ToString("yyyy-MM-dd")" readonly />
                    </div>

                    <div class="form-group col-md-4">
                        <label class="control-label">Nhà cung cấp</label>
                        <input type="text" class="form-control" value="@Model.Supplier?.DisplayName" readonly />
                    </div>

                    <div class="form-group col-md-3">
                        <label class="control-label">Người nhập: (Quản lý)</label>
                        <input type="text" class="form-control" value="@Model.Manager?.FullName" readonly />
                    </div>

                    <div class="form-group col-12">
                        <label class="control-label">Ghi chú</label>
                        <textarea class="form-control" readonly rows="5">@Model.Note</textarea>
                    </div>
                </div>

                @* <h4 class="text-center">Chi tiết hàng hóa</h4> *@
                <table class="table table-hover table-bordered" id="sampleTable">
                    <thead>
                        <tr>
                            <th class="text-center" width="30">Mã</th>
                            <th class="text-center">Tên sản phẩm</th>
                            <th class="text-center">Ảnh</th>
                            <th class="text-center">Danh mục</th>
                            <th class="text-center">Giá bán</th>
                            <th class="text-center" width="30">SL</th>
                            <th class="text-center">Giá nhập</th>
                            <th class="text-center">Tổng giá</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Goods != null && Model.Goods.Any())
                        {
                            foreach (var goods in Model.Goods)
                            {
                                <tr>
                                    <td class="text-center">@goods.Id</td>
                                    <td class="text-center">@goods.Product?.Name</td>
                                    <td class="text-center">
                                        <img src="~/adminThienAn/image_product/@goods.Product?.MainImg" alt="Ảnh sản phẩm" style="width: 50px; height: auto;" />
                                    </td>
                                    <td class="text-center">@goods.Product?.Category?.Name</td>
                                    <td class="text-center">@goods.Product?.Price.ToString("N0")đ</td>
                                    <td class="text-center">@goods.Quantity</td>
                                    <td class="text-center">@goods.ImportPrice.ToString("N0")đ</td>
                                    <td class="text-center">@goods.TotalPrice.ToString("N0")đ</td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="8" class="text-center">Không có hàng hóa nào</td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="/adminThienAn/js/heper-upImg_Time.js"></script>

}

Views/Shipments/ListShipment.cshtml
@model IEnumerable<ThienAnFuni.Models.Shipment>
@{
    ViewData["Title"] = "Danh sách nhập hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="app-title">
    @*     <ul class="app-breadcrumb breadcrumb side">
    <li class="breadcrumb-item active"><a href="#"><b>Danh sách sản phẩm</b></a></li>
    </ul> *@
    <div id="clock"></div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="row element-button">
                    <div class="col-sm-2">
                        <a class="btn btn-add btn-sm" asp-controller="adminProducts" asp-action="Create" title="Thêm sản phẩm mới">
                            <i class="fas fa-plus"></i>
                            Tạo mới sản phẩm
                        </a>
                    </div>
                    <div class="col-sm-2">
                        <a class="btn btn-add btn-sm" asp-controller="Shipments" asp-action="Index" title="Nhập hàng">
                            <i class="fas fa-plus"></i>
                            Nhập hàng
                        </a>
                    </div>
                </div>

                <div class="row">
                    <table class="table table-hover table-bordered" id="sampleTable">
                        <thead>
                            <tr>
                                <th class="text-center" width="30">Mã</th>
                                <th class="text-center">Ngày nhập</th>
                                <th class="text-center">Người nhập</th>
                                <th class="text-center">Nhà cung cấp</th>
                                <th class="text-center">Trạng thái</th>
                                <th class="text-center">Tổng tiền</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var shipment in Model)
                            {
                                <tr>
                                    <td class="text-center">@shipment.Id</td>
                                    <td class="text-center">@shipment.ReceiptDate.ToString("dd/MM/yyyy")</td>
                                    <td class="text-center">@shipment.Manager?.FullName</td>
                                    <td class="text-center">@shipment.Supplier?.DisplayName</td>
                                    <td class="text-center">Hoàn thành</td>
                                    <td class="text-center">@shipment.TotalPrice.ToString("C0", System.Globalization.CultureInfo.GetCultureInfo("vi-VN"))</td>
                                    <td class="text-center">
                                        <a asp-controller="Shipments" asp-action="Detail" asp-route-id="@shipment.Id" class="btn btn-info btn-sm"><i class="fa fa-search" aria-hidden="true"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <div class="form-group">
            <a class="btn btn-dark" asp-action="Index"> Trở về</a>
        </div>
    </div>
</div>

@section Scripts {
    <script src="/adminThienAn/js/heper-upImg_Time.js"></script>

}